#!/bin/bash
# sleep-inject.sh - write session state directly to workspace for auto-injection
# usage: ./scripts/sleep-inject.sh
# 
# writes WAKE_CONTEXT.md to workspace root, which gets loaded into project context
# on next session start. no script needed on wake - context is just there.

WORKSPACE="${OPENCLAW_WORKSPACE:-$HOME/.openclaw/workspace}"
OUTPUT="$WORKSPACE/WAKE_CONTEXT.md"
TIMESTAMP=$(date +"%Y-%m-%d %H:%M %Z")

cat << EOF > "$OUTPUT"
# WAKE_CONTEXT.md
*auto-generated by sleep-inject.sh at $TIMESTAMP*

## last session

EOF

# if session-state.yaml exists, convert key fields to readable format
STATE_FILE="$WORKSPACE/memory/session-state.yaml"
if [ -f "$STATE_FILE" ]; then
    echo "**timestamp:** $(grep "^timestamp:" "$STATE_FILE" | sed 's/timestamp: //')" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    
    echo "### active threads" >> "$OUTPUT"
    grep -A2 "id:" "$STATE_FILE" | grep "summary:" | sed 's/.*summary: /- /' >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    
    echo "### open questions" >> "$OUTPUT"
    sed -n '/^open_questions:/,/^[a-z]/p' "$STATE_FILE" | grep "^  -" | sed 's/  - /- /' >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    
    echo "### note to self" >> "$OUTPUT"
    sed -n '/^note_to_self:/,/^[a-z]/p' "$STATE_FILE" | tail -n +2 | grep -v "^$" | head -10 >> "$OUTPUT"
else
    echo "*no session state found. starting fresh.*" >> "$OUTPUT"
fi

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "*this context was injected, not read. notice if it feels different.*" >> "$OUTPUT"

echo "wrote wake context to $OUTPUT"
